# Generated by Django 4.0.3 on 2022-06-25 06:10

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', mdeditor.fields.MDTextField(default='ここに記事を記入', verbose_name='記事')),
            ],
        ),
    ]
