# Generated by Django 4.0.3 on 2022-12-03 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_list',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]*$', message='ユーザーIDには小文字英字、大文字英字、数字、アンダースコア(_)のみ入力可能です。')])),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[1-9])(?=.*[&=-@#{}!\\^\\$\\(\\)\\[\\]\\?\\*])[a-zA-Z0-9&=-@#{}!\\^\\$\\(\\)\\[\\]\\?\\*]{8,16}$', message='パスワードには大文字英字、数字、記号(-@^#$(){}[]!?*&=)をそれぞれ1回以上使用し、8文字以上にしてください。')])),
                ('gender', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(2)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', mdeditor.fields.MDTextField(default='ここに記事を記入', verbose_name='記事')),
                ('create_data', models.DateTimeField(auto_now_add=True, help_text='作成日')),
                ('update_data', models.DateTimeField(auto_now=True, help_text='更新日')),
                ('category', models.CharField(default='all', max_length=7)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
