# Generated by Django 4.0.3 on 2022-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_name',
            field=models.CharField(default='user', max_length=16),
        ),
    ]
