# Generated by Django 4.0.3 on 2022-12-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='content',
        ),
    ]
