# Generated by Django 4.0.3 on 2022-06-27 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0002_article_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='作成日'),
            preserve_default=False,
        ),
    ]
