# Generated by Django 4.0.3 on 2022-07-18 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0002_rename_user_name_users_list_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_list',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*[A-Z])(?=.*[1-9])(?=.*[&=-@#{}!\\^\\$\\(\\)\\[\\]\\?\\*])[a-zA-Z0-9&=-@#{}!\\^\\$\\(\\)\\[\\]\\?\\*]{8,16}$', message='パスワードには大文字英字、数字、記号(-@^#$(){}[]!?*&=)をそれぞれ1回以上使用し、8文字以上、16文字以内にしてください。')]),
        ),
    ]
