# Generated by Django 4.0.3 on 2022-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0003_article_create_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_data',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日'),
        ),
    ]
