# Generated by Django 4.0.3 on 2022-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0004_alter_article_create_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_data',
            field=models.DateTimeField(auto_now=True, help_text='更新日'),
        ),
    ]
