# Generated by Django 4.0.3 on 2022-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muscle_app', '0005_article_update_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='all', max_length=7),
        ),
    ]
